services:
    agent:
        build:
            context: ./
            dockerfile: ./dockerfile
        container_name: agent
        depends_on:
            - mongo
        ports:
            - 4242:4242
        tty: true
        command: python -m deeppavlov_agent.run -ch http_client --cors
    skill:
        build:
            context: ./
            dockerfile: ./dockerfile
        command: python skills/valentines_day_skill/server.py
    mongo:
        command: mongod
        image: mongo:4.0.0
        ports:
            - 27017:27017
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    nemo:
        command: uvicorn main:app --host 0.0.0.0 --reload --port 4343
        build:
            context: nemo
        depends_on:
            - agent
        ports:
            - 4343:4343
version: "3.7"
