services:
  agent:
    build:
      context: agent
    container_name: agent
    depends_on:
      - mongo
    ports:
      - 4242:4242
    tty: true
    command: python -m deeppavlov_agent.run -ch http_client --cors
  mongo:
    command: mongod
    image: mongo:4.0.0
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  trivial_response_selector:
    build:
      context: selectors/trivial_response_selector
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3003
    volumes: []
    ports:
      - 3003:3003
  harvesters_maintenance_gobot_skill:
    build:
      context: skills/harvesters_maintenance_gobot_skill
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3008 --timeout=1000
    ports:
      - 3008:3008
version: "3.7"
